#!/bin/bash -e

echo "setting up firewall iptables logging"
cat > /etc/firewall.conf <<EOL
# Generated by iptables-save v1.8.7 on Sun Jun 25 21:59:03 2023
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Sun Jun 25 21:59:03 2023
# Generated by iptables-save v1.8.7 on Sun Jun 25 21:59:03 2023
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 25 -m state --state NEW -j LOG --log-prefix "New SMTP connection "
-A INPUT -p tcp -m tcp --dport 23 -m state --state NEW -j LOG --log-prefix "New TELNET connection "
-A INPUT -p tcp -m tcp --dport 161 -m state --state NEW -j LOG --log-prefix "New SNMP connection "
-A INPUT -p tcp -m tcp --dport 123 -m state --state NEW -j LOG --log-prefix "New NTP connection "
-A INPUT -p tcp -m tcp --dport 53 -m state --state NEW -j LOG --log-prefix "New DNS connection "
-A INPUT -p tcp -m tcp --sport 20 -m state --state NEW -j LOG --log-prefix "New FTP connection "
-A INPUT -p tcp -m tcp --dport 21 -m state --state NEW -j LOG --log-prefix "New FTP connection "
-A INPUT -p tcp -m tcp --dport 443 -m state --state NEW -j LOG --log-prefix "New HTTPS connection "
-A INPUT -p tcp -m tcp --dport 80 -m state --state NEW -j LOG --log-prefix "New HTTP connection "
-A INPUT -p tcp -m tcp --dport 22 -m state --state NEW -j LOG --log-prefix "New SSH connection "
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 21 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -p udp -m udp --dport 123 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 161 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 23 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 25 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m state --state NEW -j LOG --log-prefix "INCOMING connection "
-A OUTPUT -p tcp -m tcp --sport 20 -j ACCEPT
COMMIT
# Completed on Sun Jun 25 21:59:03 2023
# Generated by iptables-save v1.8.7 on Sun Jun 25 21:59:03 2023
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Sun Jun 25 21:59:03 2023
EOL

echo '#!/bin/sh' > /etc/network/if-up.d/iptables
echo "iptables-restore < /etc/firewall.conf" >> /etc/network/if-up.d/iptables
chmod +x /etc/network/if-up.d/iptables

echo "rename pi user into cyberjutsuka and set password"

if id pi; then 
  usermod --login cyberjutsuka pi
fi
echo "cyberjutsuka:hajime" | chpasswd

echo "setting up web server apache2"
usermod -a -G www-data cyberjutsuka
chown -R -f www-data:www-data /var/www/html

sed -i 's/ServerToken OS/#ServerToken OS/' /etc/apache2/conf-enabled/security.conf
sed -i 's/#ServerToken Full/ServerToken Full/' /etc/apache2/conf-enabled/security.conf
sed -i 's/TraceEnabled Off/#TraceEnabled Off/' /etc/apache2/conf-enabled/security.conf
sed -i 's/#TraceEnabled On/TraceEnabled On/' /etc/apache2/conf-enabled/security.conf

cat > /etc/apache2/sites-available/001-cyberjutsu.conf <<EOL
<VirtualHost *:80>

  LogLevel info
  LogFormat "%h %l %u %t \"%r\" %>s %b" comm
  LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" combined
  LogFormat "%t %h %m \"%r\"" custom
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/common.log common
  CustomLog ${APACHE_LOG_DIR}/access.log combined
  CustomLog ${APACHE_LOG_DIR}/custom.log custom

  <Location /server-status>
    SetHandler server-status
    Order allow,deny
    Allow from all
  </Location>

  <Directory />
    Options All
    AllowOverride All
    Require all granted
    Order allow,deny
    DocumentRoot /var/www/html
  </Directory>

</VirtualHost>
EOL

a2dissite 000-default
a2dissite default-ssl
a2ensite 001-cyberjutsu

echo "setting up ftp server"
groupadd -f ftpgroup
usermod -a -G ftpgroup cyberjutsuka

echo "enable wireless"
rfkill unblock all
